module Grammar.Imperfecto exposing (..)

import Html exposing (Html, a, div, span, text)
import Html.Attributes exposing (..)
import I18Next exposing (Translations)
import Translations.Grammar
import Translations.SpanishGrammar


spanishImperfecto : String -> I18Next.Translations -> Html msg
spanishImperfecto exerciseListLink translations =
    div [ class "grammar-topic" ]
        [ div [ class "grammar-topic-name" ]
            [ text "Pretérito Imperfecto" ]
        , div [ class "grammar-topic-description" ]
            [ a
                [ class "grammar-to-exercises-link"
                , href exerciseListLink
                ]
                [ text <| Translations.Grammar.clickToPractice translations ]
            ]
        , div [ class "grammar-topic-content" ]
            [ div [ class "grammar-topic-section" ]
                [ div [ class "grammar-topic-section-title" ]
                    [ text <| Translations.SpanishGrammar.regularVerbs translations ]
                , div [ class "grammar-topic-section-content" ]
                    [ div [ class "grammar-topic-subsection" ]
                        [ div [ class "grammar-topic-subsection-title" ]
                            [ text <| Translations.SpanishGrammar.xxVerbsPrefix translations
                            , span [ class "grammar-topic-verb-form-ending" ]
                                [ text "-ar" ]
                            , text <| Translations.SpanishGrammar.xxVerbsSuffix translations
                            ]
                        , div [ class "grammar-topic-verb-conjugation" ]
                            [ div [ class "grammar-topic-verb" ]
                                [ text "Hablar" ]
                            , div [ class "grammar-topic-verb-forms" ]
                                [ div [ class "grammar-topic-verb-form" ]
                                    [ text "habl"
                                    , span [ class "grammar-topic-verb-form-ending" ]
                                        [ text "aba" ]
                                    ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "habl"
                                    , span [ class "grammar-topic-verb-form-ending" ]
                                        [ text "abas" ]
                                    ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "habl"
                                    , span [ class "grammar-topic-verb-form-ending" ]
                                        [ text "aba" ]
                                    ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "habl"
                                    , span [ class "grammar-topic-verb-form-ending" ]
                                        [ text "ábamos" ]
                                    ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "habl"
                                    , span [ class "grammar-topic-verb-form-ending" ]
                                        [ text "abais" ]
                                    ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "habl"
                                    , span [ class "grammar-topic-verb-form-ending" ]
                                        [ text "aban" ]
                                    ]
                                ]
                            ]
                        ]
                    , div [ class "grammar-topic-subsection" ]
                        [ div [ class "grammar-topic-subsection-title" ]
                            [ text <| Translations.SpanishGrammar.xxVerbsPrefix translations
                            , span [ class "grammar-topic-verb-form-ending" ]
                                [ text "-er" ]
                            , text <| Translations.SpanishGrammar.xxVerbsSuffix translations
                            ]
                        , div [ class "grammar-topic-verb-conjugation" ]
                            [ div [ class "grammar-topic-verb" ]
                                [ text "Comer" ]
                            , div [ class "grammar-topic-verb-forms" ]
                                [ div [ class "grammar-topic-verb-form" ]
                                    [ text "com"
                                    , span [ class "grammar-topic-verb-form-ending" ]
                                        [ text "ía" ]
                                    ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "com"
                                    , span [ class "grammar-topic-verb-form-ending" ]
                                        [ text "ías" ]
                                    ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "com"
                                    , span [ class "grammar-topic-verb-form-ending" ]
                                        [ text "ía" ]
                                    ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "com"
                                    , span [ class "grammar-topic-verb-form-ending" ]
                                        [ text "íamos" ]
                                    ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "com"
                                    , span [ class "grammar-topic-verb-form-ending" ]
                                        [ text "íais" ]
                                    ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "com"
                                    , span [ class "grammar-topic-verb-form-ending" ]
                                        [ text "ían" ]
                                    ]
                                ]
                            ]
                        ]
                    , div [ class "grammar-topic-subsection" ]
                        [ div [ class "grammar-topic-subsection-title" ]
                            [ text <| Translations.SpanishGrammar.xxVerbsPrefix translations
                            , span [ class "grammar-topic-verb-form-ending" ]
                                [ text "-ir" ]
                            , text <| Translations.SpanishGrammar.xxVerbsSuffix translations
                            ]
                        , div [ class "grammar-topic-verb-conjugation" ]
                            [ div [ class "grammar-topic-verb" ]
                                [ text "Escribir" ]
                            , div [ class "grammar-topic-verb-forms" ]
                                [ div [ class "grammar-topic-verb-form" ]
                                    [ text "escrib"
                                    , span [ class "grammar-topic-verb-form-ending" ]
                                        [ text "ía" ]
                                    ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "escrib"
                                    , span [ class "grammar-topic-verb-form-ending" ]
                                        [ text "ías" ]
                                    ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "escrib"
                                    , span [ class "grammar-topic-verb-form-ending" ]
                                        [ text "ía" ]
                                    ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "escrib"
                                    , span [ class "grammar-topic-verb-form-ending" ]
                                        [ text "íamos" ]
                                    ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "escrib"
                                    , span [ class "grammar-topic-verb-form-ending" ]
                                        [ text "íais" ]
                                    ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "escrib"
                                    , span [ class "grammar-topic-verb-form-ending" ]
                                        [ text "ían" ]
                                    ]
                                ]
                            ]
                        ]
                    ]
                ]
            , div [ class "grammar-topic-section" ]
                [ div [ class "grammar-topic-section-title" ]
                    [ text <| Translations.SpanishGrammar.irregularVerbsIrSerVer translations ]
                , div [ class "grammar-topic-section-content" ]
                    [ div [ class "grammar-topic-subsection" ]
                        [ div [ class "grammar-topic-verb-conjugation" ]
                            [ div [ class "grammar-topic-verb" ]
                                [ text "Ir" ]
                            , div [ class "grammar-topic-verb-forms" ]
                                [ div [ class "grammar-topic-verb-form" ]
                                    [ text "iba" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "ibas" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "iba" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "íbamos" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "ibais" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "iban" ]
                                ]
                            ]
                        ]
                    , div [ class "grammar-topic-subsection" ]
                        [ div [ class "grammar-topic-verb-conjugation" ]
                            [ div [ class "grammar-topic-verb" ]
                                [ text "Ser" ]
                            , div [ class "grammar-topic-verb-forms" ]
                                [ div [ class "grammar-topic-verb-form" ]
                                    [ text "era" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "eras" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "era" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "éramos" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "erais" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "eran" ]
                                ]
                            ]
                        ]
                    , div [ class "grammar-topic-subsection" ]
                        [ div [ class "grammar-topic-verb-conjugation" ]
                            [ div [ class "grammar-topic-verb" ]
                                [ text "Ver" ]
                            , div [ class "grammar-topic-verb-forms" ]
                                [ div [ class "grammar-topic-verb-form" ]
                                    [ text "veía" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "veías" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "veía" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "veíamos" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "veíais" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "veían" ]
                                ]
                            ]
                        ]
                    ]
                ]
            ]
        ]
