module Grammar.Indefinido exposing (..)

import Html exposing (Html, a, div, span, text)
import Html.Attributes exposing (..)
import I18Next exposing (Translations)
import Translations.Grammar
import Translations.SpanishGrammar


spanishIndefinido : String -> Translations -> Html msg
spanishIndefinido exerciseListLink translations =
    div [ class "grammar-topic" ]
        [ div [ class "grammar-topic-name" ]
            [ text "Pretérito Indefinido" ]
        , div [ class "grammar-topic-description" ]
            [ a
                [ class "grammar-to-exercises-link"
                , href exerciseListLink
                ]
                [ text <| Translations.Grammar.clickToPractice translations ]
            ]
        , div [ class "grammar-topic-content" ]
            [ div [ class "grammar-topic-section" ]
                [ div [ class "grammar-topic-section-title" ]
                    [ text <| Translations.SpanishGrammar.regularVerbs translations ]
                , div [ class "grammar-topic-section-content" ]
                    [ div [ class "grammar-topic-subsection" ]
                        [ div [ class "grammar-topic-subsection-title" ]
                            [ text <| Translations.SpanishGrammar.xxVerbsPrefix translations
                            , span [ class "grammar-topic-verb-form-ending" ]
                                [ text "-ar" ]
                            , text <| Translations.SpanishGrammar.xxVerbsSuffix translations
                            ]
                        , div [ class "grammar-topic-verb-conjugation" ]
                            [ div [ class "grammar-topic-verb" ]
                                [ text "Hablar" ]
                            , div [ class "grammar-topic-verb-forms" ]
                                [ div [ class "grammar-topic-verb-form" ]
                                    [ text "habl"
                                    , span [ class "grammar-topic-verb-form-ending" ]
                                        [ text "é" ]
                                    ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "habl"
                                    , span [ class "grammar-topic-verb-form-ending" ]
                                        [ text "aste" ]
                                    ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "habl"
                                    , span [ class "grammar-topic-verb-form-ending" ]
                                        [ text "ó" ]
                                    ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "habl"
                                    , span [ class "grammar-topic-verb-form-ending" ]
                                        [ text "amos" ]
                                    ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "habl"
                                    , span [ class "grammar-topic-verb-form-ending" ]
                                        [ text "asteis" ]
                                    ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "habl"
                                    , span [ class "grammar-topic-verb-form-ending" ]
                                        [ text "aron" ]
                                    ]
                                ]
                            ]
                        ]
                    , div [ class "grammar-topic-subsection" ]
                        [ div [ class "grammar-topic-subsection-title" ]
                            [ text <| Translations.SpanishGrammar.xxVerbsPrefix translations
                            , span [ class "grammar-topic-verb-form-ending" ]
                                [ text "-er" ]
                            , text <| Translations.SpanishGrammar.xxVerbsSuffix translations
                            ]
                        , div [ class "grammar-topic-verb-conjugation" ]
                            [ div [ class "grammar-topic-verb" ]
                                [ text "Comer" ]
                            , div [ class "grammar-topic-verb-forms" ]
                                [ div [ class "grammar-topic-verb-form" ]
                                    [ text "com"
                                    , span [ class "grammar-topic-verb-form-ending" ]
                                        [ text "í" ]
                                    ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "com"
                                    , span [ class "grammar-topic-verb-form-ending" ]
                                        [ text "iste" ]
                                    ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "com"
                                    , span [ class "grammar-topic-verb-form-ending" ]
                                        [ text "ió" ]
                                    ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "com"
                                    , span [ class "grammar-topic-verb-form-ending" ]
                                        [ text "imos" ]
                                    ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "com"
                                    , span [ class "grammar-topic-verb-form-ending" ]
                                        [ text "isteis" ]
                                    ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "com"
                                    , span [ class "grammar-topic-verb-form-ending" ]
                                        [ text "ieron" ]
                                    ]
                                ]
                            ]
                        ]
                    , div [ class "grammar-topic-subsection" ]
                        [ div [ class "grammar-topic-subsection-title" ]
                            [ text <| Translations.SpanishGrammar.xxVerbsPrefix translations
                            , span [ class "grammar-topic-verb-form-ending" ]
                                [ text "-ir" ]
                            , text <| Translations.SpanishGrammar.xxVerbsSuffix translations
                            ]
                        , div [ class "grammar-topic-verb-conjugation" ]
                            [ div [ class "grammar-topic-verb" ]
                                [ text "Escribir" ]
                            , div [ class "grammar-topic-verb-forms" ]
                                [ div [ class "grammar-topic-verb-form" ]
                                    [ text "escrib"
                                    , span [ class "grammar-topic-verb-form-ending" ]
                                        [ text "í" ]
                                    ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "escrib"
                                    , span [ class "grammar-topic-verb-form-ending" ]
                                        [ text "iste" ]
                                    ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "escrib"
                                    , span [ class "grammar-topic-verb-form-ending" ]
                                        [ text "ió" ]
                                    ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "escrib"
                                    , span [ class "grammar-topic-verb-form-ending" ]
                                        [ text "imos" ]
                                    ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "escrib"
                                    , span [ class "grammar-topic-verb-form-ending" ]
                                        [ text "isteis" ]
                                    ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "escrib"
                                    , span [ class "grammar-topic-verb-form-ending" ]
                                        [ text "ieron" ]
                                    ]
                                ]
                            ]
                        ]
                    ]
                ]
            , div [ class "grammar-topic-section" ]
                [ div [ class "grammar-topic-section-title" ]
                    [ text <| Translations.SpanishGrammar.radicalChangingVerbs translations ]
                , div [ class "grammar-topic-section-content" ]
                    [ div [ class "grammar-topic-subsection" ]
                        [ div [ class "grammar-topic-subsection-title" ]
                            [ text "e -> "
                            , span [ class "grammar-topic-irregular" ]
                                [ text "i" ]
                            ]
                        , div [ class "grammar-topic-verb-conjugation" ]
                            [ div [ class "grammar-topic-verb" ]
                                [ text "Sentir" ]
                            , div [ class "grammar-topic-verb-forms" ]
                                [ div [ class "grammar-topic-verb-form" ]
                                    [ text "sent"
                                    , span [ class "grammar-topic-verb-form-ending" ]
                                        [ text "í" ]
                                    ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "sent"
                                    , span [ class "grammar-topic-verb-form-ending" ]
                                        [ text "iste" ]
                                    ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "s"
                                    , span [ class "grammar-topic-irregular" ]
                                        [ text "i" ]
                                    , text "nt"
                                    , span [ class "grammar-topic-verb-form-ending" ]
                                        [ text "ió" ]
                                    ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "sent"
                                    , span [ class "grammar-topic-verb-form-ending" ]
                                        [ text "imos" ]
                                    ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "sent"
                                    , span [ class "grammar-topic-verb-form-ending" ]
                                        [ text "isteis" ]
                                    ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "s"
                                    , span [ class "grammar-topic-irregular" ]
                                        [ text "i" ]
                                    , text "nt"
                                    , span [ class "grammar-topic-verb-form-ending" ]
                                        [ text "ieron" ]
                                    ]
                                ]
                            ]
                        ]
                    , div [ class "grammar-topic-subsection" ]
                        [ div [ class "grammar-topic-subsection-title" ]
                            [ text "e -> "
                            , span [ class "grammar-topic-irregular" ]
                                [ text "i" ]
                            ]
                        , div [ class "grammar-topic-verb-conjugation" ]
                            [ div [ class "grammar-topic-verb" ]
                                [ text "Pedir" ]
                            , div [ class "grammar-topic-verb-forms" ]
                                [ div [ class "grammar-topic-verb-form" ]
                                    [ text "ped"
                                    , span [ class "grammar-topic-verb-form-ending" ]
                                        [ text "í" ]
                                    ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "ped"
                                    , span [ class "grammar-topic-verb-form-ending" ]
                                        [ text "iste" ]
                                    ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "p"
                                    , span [ class "grammar-topic-irregular" ]
                                        [ text "i" ]
                                    , text "d"
                                    , span [ class "grammar-topic-verb-form-ending" ]
                                        [ text "ió" ]
                                    ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "ped"
                                    , span [ class "grammar-topic-verb-form-ending" ]
                                        [ text "imos" ]
                                    ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "ped"
                                    , span [ class "grammar-topic-verb-form-ending" ]
                                        [ text "isteis" ]
                                    ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "p"
                                    , span [ class "grammar-topic-irregular" ]
                                        [ text "i" ]
                                    , text "d"
                                    , span [ class "grammar-topic-verb-form-ending" ]
                                        [ text "ieron" ]
                                    ]
                                ]
                            ]
                        ]
                    , div [ class "grammar-topic-subsection" ]
                        [ div [ class "grammar-topic-subsection-title" ]
                            [ text "e -> "
                            , span [ class "grammar-topic-irregular" ]
                                [ text "i" ]
                            ]
                        , div [ class "grammar-topic-verb-conjugation" ]
                            [ div [ class "grammar-topic-verb" ]
                                [ text "Servir" ]
                            , div [ class "grammar-topic-verb-forms" ]
                                [ div [ class "grammar-topic-verb-form" ]
                                    [ text "serv"
                                    , span [ class "grammar-topic-verb-form-ending" ]
                                        [ text "í" ]
                                    ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "serv"
                                    , span [ class "grammar-topic-verb-form-ending" ]
                                        [ text "iste" ]
                                    ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "s"
                                    , span [ class "grammar-topic-irregular" ]
                                        [ text "i" ]
                                    , text "rv"
                                    , span [ class "grammar-topic-verb-form-ending" ]
                                        [ text "ió" ]
                                    ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "serv"
                                    , span [ class "grammar-topic-verb-form-ending" ]
                                        [ text "imos" ]
                                    ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "serv"
                                    , span [ class "grammar-topic-verb-form-ending" ]
                                        [ text "isteis" ]
                                    ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "s"
                                    , span [ class "grammar-topic-irregular" ]
                                        [ text "i" ]
                                    , text "rv"
                                    , span [ class "grammar-topic-verb-form-ending" ]
                                        [ text "ieron" ]
                                    ]
                                ]
                            ]
                        ]
                    , div [ class "grammar-topic-subsection" ]
                        [ div [ class "grammar-topic-subsection-title" ]
                            [ text "o -> "
                            , span [ class "grammar-topic-irregular" ]
                                [ text "u" ]
                            ]
                        , div [ class "grammar-topic-verb-conjugation" ]
                            [ div [ class "grammar-topic-verb" ]
                                [ text "Dormir" ]
                            , div [ class "grammar-topic-verb-forms" ]
                                [ div [ class "grammar-topic-verb-form" ]
                                    [ text "dorm"
                                    , span [ class "grammar-topic-verb-form-ending" ]
                                        [ text "í" ]
                                    ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "dorm"
                                    , span [ class "grammar-topic-verb-form-ending" ]
                                        [ text "iste" ]
                                    ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "d"
                                    , span [ class "grammar-topic-irregular" ]
                                        [ text "u" ]
                                    , text "rm"
                                    , span [ class "grammar-topic-verb-form-ending" ]
                                        [ text "ió" ]
                                    ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "dorm"
                                    , span [ class "grammar-topic-verb-form-ending" ]
                                        [ text "imos" ]
                                    ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "dorm"
                                    , span [ class "grammar-topic-verb-form-ending" ]
                                        [ text "isteis" ]
                                    ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "d"
                                    , span [ class "grammar-topic-irregular" ]
                                        [ text "u" ]
                                    , text "rm"
                                    , span [ class "grammar-topic-verb-form-ending" ]
                                        [ text "ieron" ]
                                    ]
                                ]
                            ]
                        ]
                    ]
                ]
            , div [ class "grammar-topic-section" ]
                [ div [ class "grammar-topic-section-title" ]
                    [ text <| Translations.SpanishGrammar.irregularVerbsIrSerEstar translations ]
                , div [ class "grammar-topic-section-content" ]
                    [ div [ class "grammar-topic-subsection" ]
                        [ div [ class "grammar-topic-verb-conjugation" ]
                            [ div [ class "grammar-topic-verb" ]
                                [ text "Ir" ]
                            , div [ class "grammar-topic-verb-forms" ]
                                [ div [ class "grammar-topic-verb-form" ]
                                    [ text "fui" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "fuiste" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "fue" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "fuimos" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "fuisteis" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "fueron" ]
                                ]
                            ]
                        ]
                    , div [ class "grammar-topic-subsection" ]
                        [ div [ class "grammar-topic-verb-conjugation" ]
                            [ div [ class "grammar-topic-verb" ]
                                [ text "Ser" ]
                            , div [ class "grammar-topic-verb-forms" ]
                                [ div [ class "grammar-topic-verb-form" ]
                                    [ text "fui" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "fuiste" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "fue" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "fuimos" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "fuisteis" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "fueron" ]
                                ]
                            ]
                        ]
                    , div [ class "grammar-topic-subsection" ]
                        [ div [ class "grammar-topic-verb-conjugation" ]
                            [ div [ class "grammar-topic-verb" ]
                                [ text "Estar" ]
                            , div [ class "grammar-topic-verb-forms" ]
                                [ div [ class "grammar-topic-verb-form" ]
                                    [ text "estuve" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "estuviste" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "estuvo" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "estuvimos" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "estuvisteis" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "estuvieron" ]
                                ]
                            ]
                        ]
                    ]
                ]
            , div [ class "grammar-topic-section" ]
                [ div [ class "grammar-topic-section-title" ]
                    [ text <| Translations.SpanishGrammar.irregularVerbsDarTenerPoner translations ]
                , div [ class "grammar-topic-section-content" ]
                    [ div [ class "grammar-topic-subsection" ]
                        [ div [ class "grammar-topic-verb-conjugation" ]
                            [ div [ class "grammar-topic-verb" ]
                                [ text "Dar" ]
                            , div [ class "grammar-topic-verb-forms" ]
                                [ div [ class "grammar-topic-verb-form" ]
                                    [ text "di" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "diste" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "dio" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "dimos" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "disteis" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "dieron" ]
                                ]
                            ]
                        ]
                    , div [ class "grammar-topic-subsection" ]
                        [ div [ class "grammar-topic-verb-conjugation" ]
                            [ div [ class "grammar-topic-verb" ]
                                [ text "Tener" ]
                            , div [ class "grammar-topic-verb-forms" ]
                                [ div [ class "grammar-topic-verb-form" ]
                                    [ text "tuve" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "tuviste" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "tuvo" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "tuvimos" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "tuvisteis" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "tuvieron" ]
                                ]
                            ]
                        ]
                    , div [ class "grammar-topic-subsection" ]
                        [ div [ class "grammar-topic-verb-conjugation" ]
                            [ div [ class "grammar-topic-verb" ]
                                [ text "Poner" ]
                            , div [ class "grammar-topic-verb-forms" ]
                                [ div [ class "grammar-topic-verb-form" ]
                                    [ text "puse" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "pusiste" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "puso" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "pusimos" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "pusisteis" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "pusieron" ]
                                ]
                            ]
                        ]
                    ]
                ]
            , div [ class "grammar-topic-section" ]
                [ div [ class "grammar-topic-section-title" ]
                    [ text <| Translations.SpanishGrammar.irregularVerbsHacerSaberVenir translations ]
                , div [ class "grammar-topic-section-content" ]
                    [ div [ class "grammar-topic-subsection" ]
                        [ div [ class "grammar-topic-verb-conjugation" ]
                            [ div [ class "grammar-topic-verb" ]
                                [ text "Hacer" ]
                            , div [ class "grammar-topic-verb-forms" ]
                                [ div [ class "grammar-topic-verb-form" ]
                                    [ text "hice" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "hiciste" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "hizo" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "hicimos" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "hicisteis" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "hicieron" ]
                                ]
                            ]
                        ]
                    , div [ class "grammar-topic-subsection" ]
                        [ div [ class "grammar-topic-verb-conjugation" ]
                            [ div [ class "grammar-topic-verb" ]
                                [ text "Saber" ]
                            , div [ class "grammar-topic-verb-forms" ]
                                [ div [ class "grammar-topic-verb-form" ]
                                    [ text "supe" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "supiste" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "supo" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "supimos" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "supisteis" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "supieron" ]
                                ]
                            ]
                        ]
                    , div [ class "grammar-topic-subsection" ]
                        [ div [ class "grammar-topic-verb-conjugation" ]
                            [ div [ class "grammar-topic-verb" ]
                                [ text "Venir" ]
                            , div [ class "grammar-topic-verb-forms" ]
                                [ div [ class "grammar-topic-verb-form" ]
                                    [ text "vine" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "viniste" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "vino" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "vinimos" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "vinisteis" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "vinieron" ]
                                ]
                            ]
                        ]
                    ]
                ]
            , div [ class "grammar-topic-section" ]
                [ div [ class "grammar-topic-section-title" ]
                    [ text <| Translations.SpanishGrammar.irregularVerbsDecirPoderQuerer translations ]
                , div [ class "grammar-topic-section-content" ]
                    [ div [ class "grammar-topic-subsection" ]
                        [ div [ class "grammar-topic-verb-conjugation" ]
                            [ div [ class "grammar-topic-verb" ]
                                [ text "Decir" ]
                            , div [ class "grammar-topic-verb-forms" ]
                                [ div [ class "grammar-topic-verb-form" ]
                                    [ text "dije" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "dijiste" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "dijo" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "dijimos" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "dijisteis" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "dijeron" ]
                                ]
                            ]
                        ]
                    , div [ class "grammar-topic-subsection" ]
                        [ div [ class "grammar-topic-verb-conjugation" ]
                            [ div [ class "grammar-topic-verb" ]
                                [ text "Poder" ]
                            , div [ class "grammar-topic-verb-forms" ]
                                [ div [ class "grammar-topic-verb-form" ]
                                    [ text "pude" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "pudiste" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "pudo" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "pudimos" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "pudisteis" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "pudieron" ]
                                ]
                            ]
                        ]
                    , div [ class "grammar-topic-subsection" ]
                        [ div [ class "grammar-topic-verb-conjugation" ]
                            [ div [ class "grammar-topic-verb" ]
                                [ text "Querer" ]
                            , div [ class "grammar-topic-verb-forms" ]
                                [ div [ class "grammar-topic-verb-form" ]
                                    [ text "quise" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "quisiste" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "quiso" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "quisimos" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "quisisteis" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "quisieron" ]
                                ]
                            ]
                        ]
                    ]
                ]
            , div [ class "grammar-topic-section" ]
                [ div [ class "grammar-topic-section-title" ]
                    [ text <| Translations.SpanishGrammar.irregularVerbsReirTraerConducir translations ]
                , div [ class "grammar-topic-section-content" ]
                    [ div [ class "grammar-topic-subsection" ]
                        [ div [ class "grammar-topic-verb-conjugation" ]
                            [ div [ class "grammar-topic-verb" ]
                                [ text "Reír" ]
                            , div [ class "grammar-topic-verb-forms" ]
                                [ div [ class "grammar-topic-verb-form" ]
                                    [ text "reí" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "reíste" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "rió" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "reímos" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "reísteis" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "rieron" ]
                                ]
                            ]
                        ]
                    , div [ class "grammar-topic-subsection" ]
                        [ div [ class "grammar-topic-verb-conjugation" ]
                            [ div [ class "grammar-topic-verb" ]
                                [ text "Traer" ]
                            , div [ class "grammar-topic-verb-forms" ]
                                [ div [ class "grammar-topic-verb-form" ]
                                    [ text "traje" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "trajiste" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "trajo" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "trajimos" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "trajisteis" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "trajeron" ]
                                ]
                            ]
                        ]
                    , div [ class "grammar-topic-subsection" ]
                        [ div [ class "grammar-topic-verb-conjugation" ]
                            [ div [ class "grammar-topic-verb" ]
                                [ text "Conducir" ]
                            , div [ class "grammar-topic-verb-forms" ]
                                [ div [ class "grammar-topic-verb-form" ]
                                    [ text "conduje" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "condujiste" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "condujo" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "condujimos" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "condujisteis" ]
                                , div [ class "grammar-topic-verb-form" ]
                                    [ text "condujeron" ]
                                ]
                            ]
                        ]
                    ]
                ]
            ]
        ]
